#commands that specify the language

language: python
python: 
- "3.6"



#command that installs dependancies
install: 
- pip install -r requirements.txt


# command to run tests
script : 
-  nosetests --exe -v --with-coverage --cover-package=app

after_success:
- coveralls




